[core]
title = "Set Custom Metadata"

[metadata]
description = "Universal Scene Description (OpenUSD) code samples for setting custom metadata."
keywords = ["OpenUSD", "USD", "Python", "code sample", "snippet", "set", "custom", "metadata"]