name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install project
      run: poetry install --no-interaction
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "poetry run python build_docs.py"
        docs-folder: "sphinx/"